name: Delete branch after merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: peter-evans/delete-branch@v2
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
