name: Build and Deploy to Vercel (with Prisma generate on Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: TypeScript typecheck
        run: |
          npx tsc --noEmit

      - name: Lint
        run: |
          npm run lint

      - name: Run Prisma Generate (Linux)
        env:
          PRISMA_SCHEMA: prisma/schema.vercel.prisma
        run: |
          npx prisma generate --schema=prisma/schema.vercel.prisma

      - name: Build
        run: |
          npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token "$VERCEL_TOKEN" --confirm
